name: release
on:
  push:
    tags: 'r*'
jobs:
  build-receiver-pico:
    uses: ./.github/workflows/build-receiver-pico.yml
  create-release:
    needs: build-receiver-pico
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: download
          merge-multiple: true
      - uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          draft: true
          files: download/*
